url: https://Madhuri1518.github.io
baseurl: /agency-jekyll-theme/
# Site settings
title: My Blog
email: madhuri.kotha@zemosolabs.com
description: ""


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Madhurikotha6
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/Madhuri1518

# Postal address (add as many lines as necessary)
address:
  - line: Gachibowli
  - line: Hyderabad, Telangana

# Build settings
markdown: kramdown
permalink: pretty
