url: https://Madhuri1518.github.io
baseurl: ""
# Site settings
title: My Blog
email: madhuri.kotha@zemosolabs.com
description: ""


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Madhurikotha6
  - title: linkedin
    url: https://www.linkedin.com/in/madhuri-kotha-92851b165
  - title: github
    url: https://github.com/Madhuri1518

# Postal address (add as many lines as necessary)
address:
  - line: Gachibowli
  - line: Hyderabad, Telangana

# Build settings
markdown: kramdown
permalink: pretty
